# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
#- bash: echo "##vso[task.prependpath]$CONDA/bin"
#  displayName: Add conda to PATH (CondaToolInstaller@0)

#- bash: echo "##vso[task.setvariable variable=CONDA_VERBOSITY;]2"
#  displayName: Set conda verbosity

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      conda create --offline --name AZDO -y
      conda config --show
  displayName: Create conda environment

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      prefix = (Get-CondaEnvironment | Where-Object Name -eq '{ENV}').Path
      Copy-Item -LiteralPath '{CONDARC}' -Destination (Join-Path $prefix '.condarc')
      conda config --show
  displayName: Attaching .condarc to environment

- task: PowerShell@2
  inputs:
    targetType: inline
    script: conda config --show
  env: 
    ARTIFACTS_CONDA_TOKEN: $(System.AccessToken)
  displayName: Set up auth token (CondaAuthenticate@0)

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      source activate AZDO
      conda install numpy -y
  displayName: Activating and Using Conda environment