# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
#- bash: echo "##vso[task.prependpath]$CONDA/bin"
#  displayName: Add conda to PATH (CondaToolInstaller@0)

#- bash: echo "##vso[task.setvariable variable=CONDA_VERBOSITY;]2"
#  displayName: Set conda verbosity

- powershell: |
    . $env:CONDA/shell/condabin/conda-hook.ps1
    conda create --yes --quiet --offline --name AZDO
    $prefix = (Get-CondaEnvironment | Where-Object Name -eq 'AZDO').Path
    Copy-Item -LiteralPath '.condarc' -Destination (Join-Path $prefix '.condarc')
  displayName: Create Conda environment

- powershell:  Write-Host "##vso[task.setvariable variable=ARTIFACTS_CONDA_TOKEN;]$(System.AccessToken)"
  displayName: Set up auth token (CondaAuthenticate@0)








