name: Bug
description: Report a bug 
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form if you'd like to report bug related to one of the 
        tasks. [List of the tasks](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks)
  - type: input
    id: task-name
    attributes:
      label: Task name
  - type: input
    id: task-version
    attributes:
      label: Task version
      placeholder: x.x.x
  - type: markdown
    attributes:
      value: |
        ## Environment 
  - type: checkboxes
    id: environment-type
    attributes:
      label: Environment type (Please select at least one enviroment where you face this issue)
      options:
        - label: Self-Hosted
        - label: Microsoft Hosted
        - label: VMSS Pool
        - label: Container
  - type: dropdown
    id: azure-devops-type
    attributes:
      label: Azure DevOps Server type
      options:
        - dev.azure.com (formerly visualstudio.com)
        - Azure DevOps Server (Please specify exact version in the textbox below)
    validations:
      required: true
  - type: input
    id: azure-devops-server-datails
    attributes:
      label: Azure DevOps Server Version (if applicable)
      placeholder: Azure DevOps Server 2019.1
  - type: input
    id: operation-system
    attributes:
      label: Operation system
      placeholder: Windows 11, Ubuntu 20.04...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Logs 
  - type: textarea
    id: task-logs
    attributes:
      label: Task log
      description: |
        Please copy and paste any relevant log output.
      render: shell
    validations:
      required: true
  - type: textarea
    id: error-logs
    attributes:
      label: Relevant log output
      description: |
        Insert error from the logs here for a quick overview
      render: shell
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
  - type: textarea
    id: extra-details
    attributes:
      label: Aditional info
      description: |
        Paste any additional information here
      render: shell
