export declare function jacocoGradleMultiModuleEnable(excludeFilter: string, includeFilter: string, classFileDirectory: string, reportDir: string): string;
export declare function jacocoGradleSingleModuleEnable(excludeFilter: string, includeFilter: string, classFileDirectory: string, reportDir: string): string;
export declare function coberturaGradleSingleModuleEnable(excludeFilter: string, includeFilter: string, classDir: string, sourceDir: string, reportDir: string): string;
export declare function coberturaGradleMultiModuleEnable(excludeFilter: string, includeFilter: string, classDir: string, sourceDir: string, reportDir: string): string;
export declare function jacocoMavenPluginEnable(includeFilter: string[], excludeFilter: string[], outputDirectory: string): any;
export declare function jacocoMavenMultiModuleReport(reportDir: string, srcData: string, classData: string, includeFilter: string, excludeFilter: string): string;
export declare function coberturaMavenEnable(includeFilter: string, excludeFilter: string, aggregate: string): Q.Promise<any>;
export declare function coberturaMavenReport(): Q.Promise<any>;
export declare function jacocoAntReport(reportDir: string, classData: string, sourceData: string): string;
export declare function jacocoAntCoverageEnable(reportDir: string): any;
export declare function coberturaAntReport(srcDir: string, reportDir: string): string;
export declare function coberturaAntCoverageEnable(): string;
export declare function coberturaAntInstrumentedClasses(baseDir: string, reportDir: string, classData: string): any;
export declare function coberturaAntProperties(reportDir: string, baseDir: string): any;
export declare function coberturaAntClasspathRef(): string;
export declare const coberturaGradleBuildScript: string;
