import tl = require('azure-pipelines-task-lib/task');
import * as path from 'path';
import * as fs from 'fs';
import SqlConnectionConfig from './SqlConnectionConfig';

export class SqlPackageExecutor {
    /**
     * Execute SqlPackage with the specified parameters
     */
    public static async executeSqlPackage(
        sqlPackagePath: string,
        action: string,
        sourcePath: string,
        connectionConfig: SqlConnectionConfig,
        publishProfile?: string,
        additionalArguments?: string,
        accessToken?: string
    ): Promise<string | undefined> {
        // Auto-generate output path for script/deployReport if user didn't specify one
        const outputGeneratingActions = ['script', 'deployreport'];
        let resolvedAdditionalArguments = additionalArguments;
        let autoGeneratedOutputPath: string | undefined;

        if (outputGeneratingActions.includes(action.toLowerCase())) {
            const userSpecifiedOutput = this.extractOutputPath(additionalArguments);
            if (!userSpecifiedOutput) {
                const tempDir = tl.getVariable('Agent.TempDirectory') || require('os').tmpdir();
                const outputDir = path.join(tempDir, 'GeneratedOutputFiles');
                if (!fs.existsSync(outputDir)) {
                    fs.mkdirSync(outputDir, { recursive: true });
                }
                const fileExtension = action.toLowerCase() === 'deployreport' ? '.xml' : '.sql';
                autoGeneratedOutputPath = path.join(outputDir, `${action}_${Date.now()}${fileExtension}`);
                resolvedAdditionalArguments = (additionalArguments || '') + ` /OutputPath:${autoGeneratedOutputPath}`;
            }
        }

        const args = this.buildArguments(action, sourcePath, connectionConfig, publishProfile, resolvedAdditionalArguments, accessToken);

        tl.debug(`Executing SqlPackage: ${sqlPackagePath}`);

        // Capture output so we can include the real error reason in the thrown exception.
        // tl.exec streams lines to the task log as they arrive, so the user sees full output
        // regardless. We only keep the last 20 lines for the failure summary.
        const outputLines: string[] = [];
        const captureLines = (data: Buffer) => {
            const lines = data.toString().split(/\r?\n/).filter(l => l.trim());
            outputLines.push(...lines);
            if (outputLines.length > 20) { outputLines.splice(0, outputLines.length - 20); }
        };

        const result = await tl.exec(sqlPackagePath, args, {
            failOnStdErr: false,
            ignoreReturnCode: true,
            listeners: { stdout: captureLines, stderr: captureLines }
        });

        if (result !== 0) {
            const detail = outputLines.join('\n').trim();
            const message = detail
                ? `${tl.loc('SqlPackageExecutionFailed', result)}\n${detail}`
                : tl.loc('SqlPackageExecutionFailed', result);
            throw new Error(message);
        }

        // Return the output file path (user-specified or auto-generated)
        const outputPath = this.extractOutputPath(resolvedAdditionalArguments) || autoGeneratedOutputPath;
        if (outputPath && fs.existsSync(outputPath)) {
            console.log(`##vso[task.uploadfile]${outputPath}`);
        }
        return outputPath;
    }

    /**
     * Build SqlPackage command line arguments
     */
    private static buildArguments(
        action: string,
        sourcePath: string,
        connectionConfig: SqlConnectionConfig,
        publishProfile?: string,
        additionalArguments?: string,
        accessToken?: string
    ): string[] {
        const args: string[] = [];

        args.push(`/Action:${this.mapActionToSqlPackageAction(action)}`);
        args.push(`/SourceFile:${sourcePath}`);

        // Prefer access token when available; fall back to connection string
        if (accessToken) {
            args.push(`/TargetServerName:${connectionConfig.Server}`);
            args.push(`/TargetDatabaseName:${connectionConfig.Database}`);
            args.push(`/AccessToken:${accessToken}`);
        } else {
            args.push(`/TargetConnectionString:${connectionConfig.EscapedConnectionString}`);
        }

        if (publishProfile) {
            tl.checkPath(publishProfile, 'publishProfile');
            args.push(`/Profile:${publishProfile}`);
        }

        if (additionalArguments) {
            args.push(...this.parseAdditionalArguments(additionalArguments));
        }

        return args;
    }

    /**
     * Map task action name to SqlPackage /Action value
     */
    private static mapActionToSqlPackageAction(action: string): string {
        switch (action.toLowerCase()) {
            case 'publish':      return 'Publish';
            case 'script':       return 'Script';
            case 'deployreport': return 'DeployReport';
            default:
                throw new Error(tl.loc('InvalidAction', action));
        }
    }

    /**
     * Parse additional arguments string, respecting quoted values
     */
    private static parseAdditionalArguments(additionalArguments: string): string[] {
        const args: string[] = [];
        let current = '';
        let inQuotes = false;
        let quoteChar = '';

        for (const char of additionalArguments) {
            if ((char === '"' || char === "'") && !inQuotes) {
                inQuotes = true;
                quoteChar = char;
                current += char;
            } else if (char === quoteChar && inQuotes) {
                inQuotes = false;
                quoteChar = '';
                current += char;
            } else if (char === ' ' && !inQuotes) {
                if (current.trim()) {
                    args.push(current.trim());
                    current = '';
                }
            } else {
                current += char;
            }
        }

        if (current.trim()) {
            args.push(current.trim());
        }

        return args;
    }

    /**
     * Extract /OutputPath value from additional arguments if present
     */
    private static extractOutputPath(additionalArguments?: string): string | undefined {
        if (!additionalArguments) {
            return undefined;
        }
        const match = additionalArguments.match(/\/OutputPath[:\s]+"?([^"\s]+)"?/i);
        return match ? match[1] : undefined;
    }
}
