import tl = require('azure-pipelines-task-lib/task');
import * as path from 'path';
import * as fs from 'fs';
import SqlConnectionConfig from './SqlConnectionConfig';

export class SqlPackageExecutor {
    /**
     * Execute SqlPackage with the specified parameters
     */
    public static async executeSqlPackage(
        sqlPackagePath: string,
        action: string,
        sourcePath: string,
        connectionConfig: SqlConnectionConfig,
        publishProfile?: string,
        additionalArguments?: string,
        accessToken?: string
    ): Promise<string | undefined> {
        // Auto-generate output path for script/deployReport if user didn't specify one
        const outputGeneratingActions = ['script', 'deployreport'];
        let autoGeneratedOutputPath: string | undefined;

        if (outputGeneratingActions.includes(action.toLowerCase())) {
            const userSpecifiedOutput = this.extractOutputPath(additionalArguments);
            if (!userSpecifiedOutput) {
                const tempDir = tl.getVariable('Agent.TempDirectory') || require('os').tmpdir();
                const outputDir = path.join(tempDir, 'GeneratedOutputFiles');
                if (!fs.existsSync(outputDir)) {
                    fs.mkdirSync(outputDir, { recursive: true });
                }
                const fileExtension = action.toLowerCase() === 'deployreport' ? '.xml' : '.sql';
                autoGeneratedOutputPath = path.join(outputDir, `${action}_${Date.now()}${fileExtension}`);
            }
        }

        const args = this.buildArguments(action, sourcePath, connectionConfig, publishProfile, additionalArguments, accessToken, autoGeneratedOutputPath);

        tl.debug(`Executing SqlPackage: ${sqlPackagePath}`);

        // Capture the last 20 output lines for error reporting.
        // Tee to process.stdout/stderr so the full output still appears in the task log.
        const outputLines: string[] = [];
        const captureLines = (data: Buffer) => {
            const lines = data.toString().split(/\r?\n/).filter(l => l.trim());
            outputLines.push(...lines);
            if (outputLines.length > 20) { outputLines.splice(0, outputLines.length - 20); }
        };

        const result = await tl.exec(sqlPackagePath, args, {
            failOnStdErr: false,
            ignoreReturnCode: true,
            outStream: new (require('stream').Writable)({
                write(chunk: Buffer, _enc: string, cb: () => void) {
                    captureLines(chunk);
                    process.stdout.write(chunk);
                    cb();
                }
            }) as NodeJS.WritableStream,
            errStream: new (require('stream').Writable)({
                write(chunk: Buffer, _enc: string, cb: () => void) {
                    captureLines(chunk);
                    process.stderr.write(chunk);
                    cb();
                }
            }) as NodeJS.WritableStream
        });

        if (result !== 0) {
            const detail = outputLines.join('\n').trim();
            const message = detail
                ? `${tl.loc('SqlPackageExecutionFailed', result)}\n${detail}`
                : tl.loc('SqlPackageExecutionFailed', result);
            throw new Error(message);
        }

        // Upload and return the output file path only if the file was actually produced.
        // For script/deployReport the output file is the primary artifact; fail if missing.
        const outputPath = this.extractOutputPath(additionalArguments) || autoGeneratedOutputPath;
        if (outputPath) {
            if (fs.existsSync(outputPath)) {
                console.log(`##vso[task.uploadfile]${outputPath}`);
                return outputPath;
            } else if (outputGeneratingActions.includes(action.toLowerCase())) {
                throw new Error(tl.loc('OutputFileNotProduced', outputPath));
            }
        }
        return undefined;
    }

    /**
     * Build SqlPackage command line arguments
     */
    private static buildArguments(
        action: string,
        sourcePath: string,
        connectionConfig: SqlConnectionConfig,
        publishProfile?: string,
        additionalArguments?: string,
        accessToken?: string,
        autoGeneratedOutputPath?: string
    ): string[] {
        const args: string[] = [];

        args.push(`/Action:${this.mapActionToSqlPackageAction(action)}`);
        args.push(`/SourceFile:${sourcePath}`);

        // Only use /AccessToken for auth types that name no identity in the connection string
        // (AAD Default), where the identity has to come from the service connection.
        // Everything else already identifies its own principal, so use /TargetConnectionString:
        // SQL auth, AAD Password and AAD Service Principal carry credentials directly, while
        // AAD Managed Identity and AAD Integrated each name a specific identity that must not be
        // replaced by the service connection's.
        const tokenBasedAuthTypes = ['activedirectorydefault'];
        const authType = (connectionConfig.FormattedAuthentication ?? '').toLowerCase();
        const useAccessToken = !!accessToken && tokenBasedAuthTypes.includes(authType);

        if (useAccessToken) {
            // The Server getter returns the host alone, because callers such as ARM lookup and DNS
            // need it without a port. SqlPackage needs the port back: a managed instance public
            // endpoint listens on 3342, and dropping it sends the deployment to 1433 instead. The
            // sqlcmd path rebuilds it the same way.
            args.push(`/TargetServerName:${connectionConfig.Port
                ? `${connectionConfig.Server},${connectionConfig.Port}`
                : connectionConfig.Server}`);
            args.push(`/TargetDatabaseName:${connectionConfig.Database}`);
            args.push(`/AccessToken:${accessToken}`);
        } else {
            args.push(`/TargetConnectionString:${connectionConfig.ConnectionString}`);
        }

        if (publishProfile) {
            tl.checkPath(publishProfile, 'publishProfile');
            args.push(`/Profile:${publishProfile}`);
        }

        if (additionalArguments) {
            args.push(...this.parseAdditionalArguments(additionalArguments));
        }

        // Passed as its own argument rather than appended to additionalArguments, which is
        // re-parsed and split on unquoted spaces. Quoting it there does not help: the quotes
        // survive parsing, the agent quotes the argument again, and SqlPackage rejects the
        // doubled quotes as illegal path characters.
        if (autoGeneratedOutputPath) {
            args.push(`/OutputPath:${autoGeneratedOutputPath}`);
        }

        return args;
    }

    /**
     * Map task action name to SqlPackage /Action value
     */
    private static mapActionToSqlPackageAction(action: string): string {
        switch (action.toLowerCase()) {
            case 'publish':      return 'Publish';
            case 'script':       return 'Script';
            case 'deployreport': return 'DeployReport';
            default:
                throw new Error(tl.loc('InvalidAction', action));
        }
    }

    /**
     * Split an additional arguments string into argv elements.
     *
     * Quotes are treated as syntax and removed once they have done their job of keeping a value
     * together. Retaining them puts literal quote characters in the argument, and SqlPackage
     * rejects those as illegal path characters, so /OutputPath:"C:\out dir\x.sql" would fail
     * even though quoting is the documented way to pass a path containing spaces.
     */
    private static parseAdditionalArguments(additionalArguments: string): string[] {
        const args: string[] = [];
        let current = '';
        let inQuotes = false;
        let quoteChar = '';
        let hasContent = false;

        const flush = (): void => {
            if (hasContent || current.length > 0) {
                args.push(current);
            }
            current = '';
            hasContent = false;
        };

        for (const char of additionalArguments) {
            if ((char === '"' || char === "'") && !inQuotes) {
                inQuotes = true;
                quoteChar = char;
                // An empty quoted value is still a value, so remember it was quoted.
                hasContent = true;
            } else if (char === quoteChar && inQuotes) {
                inQuotes = false;
                quoteChar = '';
            } else if (char === ' ' && !inQuotes) {
                if (current.length > 0 || hasContent) {
                    flush();
                }
            } else {
                current += char;
            }
        }

        if (current.length > 0 || hasContent) {
            flush();
        }

        return args;
    }

    /**
     * Extract the user-specified output path from additional arguments, if there is one.
     *
     * Recognises both /OutputPath and its documented short form /op. Missing /op made the task
     * treat the argument as absent and append a second, auto-generated /OutputPath.
     * Handles double-quoted, single-quoted, and unquoted values.
     */
    private static extractOutputPath(additionalArguments?: string): string | undefined {
        if (!additionalArguments) {
            return undefined;
        }
        const match = additionalArguments.match(/\/(?:OutputPath|op)[:\s]+(?:"([^"]+)"|'([^']+)'|([^\s]+))/i);
        return match ? (match[1] || match[2] || match[3]) : undefined;
    }
}
