name: $(Date:MMddyy)$(Rev:.rrrr)

trigger: none

schedules:
- cron: 0 8 * * Mon # mm HH DD MM DW
  displayName: Localization update
  branches:
    include: 
    - Localization
  always: true

stages:
- stage: __default
  jobs:
  - job: Job1
    pool:
      vmImage: windows-latest
    steps:
    - powershell: |
        $week = (Invoke-WebRequest https://whatsprintis.it -Headers @{"Accept"= "application/json"} | ConvertFrom-Json).week
        Write-Host "##vso[task.setvariable variable=week]$week"
      displayName: "Determine the number of the week in the sprint"

    - powershell: |
        git config --global user.email "$(username)@microsoft.com"
        git config --global user.name "$(username)"
        git checkout -b Localization origin/Localization
        git merge origin/master
        git status
      displayName: "Sync with master branch"

    - task: OneLocBuild@2
      condition: and(succeeded(), eq(variables['WEEK'], '3'))
      inputs:
        locProj: 'Localize/LocProject.json'
        outDir: '$(Build.ArtifactStagingDirectory)'
        packageSourceAuth: 'patAuth'
        patVariable: '$(OneLocBuildPAT)'
        isCreatePrSelected: true
        repoType: 'gitHub'
        prSourceBranchPrefix: 'Localize'
        gitHubPatVariable: '$(GitHubPAT)'
        isAutoCompletePrSelected: false
      env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - powershell: |
        $body = '{"text": "Created tasks localization update PR. Someone please approve/merge it. :please-puss-in-boots:"}'
        Invoke-RestMethod -Uri $(slackUri) -Method Post -Body $body -ContentType 'application/json'
      displayName: 'Send Slack notification about PR opened'
      condition: and(succeeded(), eq(variables['WEEK'], '3'), eq(variables['build.reason'], 'Schedule'))

    - powershell: |
        $buildUrl = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&_a=summary"
        $body = '{"text": "Something went wrong while creating tasks localization update PR. Build: ' + $buildUrl + '"}'
        Invoke-RestMethod -Uri $(slackUri) -Method Post -Body $body -ContentType 'application/json'
      displayName: 'Send Slack notification about error'
      condition: and(failed(), eq(variables['WEEK'], '3'), eq(variables['build.reason'], 'Schedule'))

    - task: PublishBuildArtifacts@1
      condition: and(succeeded(), eq(variables['WEEK'], '3'))
      displayName: 'Publish Artifact: drop'

