parameters:
- name: tasks
  displayName: Build Single Task
  type: string
  default: UseNodeV1,MavenV3

trigger: none

jobs:
  - ${{ each var in split(parameters.tasks, ',') }}:
    - job: ${{ var }}_build_single_task
      strategy:
        parallel: 2
      displayName: Build Task (${{ var }})
      pool:
        vmImage: windows-2022
      steps:
      - template: ./build-single-steps.yml
        parameters:
          task: ${{ var }}
          push: false
          publishArtifact: true
          patchVersion: true
          version: '0.9999.9999'

    - job: ${{ var }}_upload_test_task
      strategy:
        parallel: 2
      displayName: Upload (${{ var }})
      dependsOn: ${{ var }}_build_single_task
      pool:
        vmImage: windows-2022
      steps:
      - template: ./publish-and-test.yml
        parameters:
          task: ${{ var }}
