variables:
  - name: tasks
    default: MavenV3

jobs:
- job: get_task_names
    # we only test tasks on a PR and ignore forks since for security reasosns PAT tokens pipeline variable will not be available for fork's PRs.
    #condition: and(eq(variables['build.reason'], 'PullRequest'), eq(variables['System.PullRequest.IsFork'], 'False')) TODO: uncomment the line after testing
    steps:
    - script: npm install @octokit/core
      displayName: 'npm install @octokit/core'
    - script: |
        echo "##vso[task.setvariable variable=tasks;isoutput=true;]task1,task2,task3"
    #    echo "##vso[task.setvariable variable=tasksnames;isoutput=true]$(node ./ci/testing/extractTaskNames.js $(PAT_Github))"
      displayName: 'Extract task names'

    - bash: |
        echo $(tasksnames)
      continueOnError: true