trigger:
  - master
  - releases/*

jobs:
- job: detect_changes
  displayName: Detect changes
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: |
      git fetch origin master
      git diff --name-only origin/master
      echo "##vso[task.setvariable variable=TASKS;isoutput=true]$(node ./ci/ci-test-tasks/detect-changed-tasks.js $(git diff --name-only origin/master))"
    displayName: 'Detect changed tasks'
    name: detect

- job: run_main_test_pipeline
  displayName: Run main test pipeline
  condition: |
    and(
      succeeded(),
      gt(length(dependencies.detect_changes.outputs['detect.TASKS']), 0)
    )
  dependsOn: detect_changes
  timeoutInMinutes: 360
  variables:
      - name: tasks
        value: $[dependencies.detect_changes.outputs['detect.TASKS']]
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    displayName: Use Node 20.x
    inputs:
      versionSpec: 20.x

  - script: |
      cd ./ci/ci-test-tasks/test-and-verify-v2
      npm i
      npm run build
    displayName: 'Build test pipelines runner'

  - script: |
      echo "Tasks to test: $(tasks)"
      node ./ci/ci-test-tasks/test-and-verify-v2 $(System.AccessToken) $(ADOUrl) $(System.TeamProject) $(tasks)
    displayName: 'Run test pipelines and verify results'
    failOnStderr: true
