parameters:
- name: includeLocalPackagesBuildConfig
  displayName: Flag to update LocalPackages buildconfig (for testing, this will be made  default later)
  type: boolean
  default: false # Note: keep in sync with /azure-pipelines.yml
- name: USE_node20
  displayName: 'Feature Flag: USE_node20'
  type: string
  default: ''
- name: usenode24withtaskhandler
  displayName: 'Feature Flag: usenode24withtaskhandler'
  type: string
  default: ''

variables:
- name: includeLocalPackagesBuildConfigParameter
  ${{ if eq(parameters.includeLocalPackagesBuildConfig, true) }}:
    value: '--includeLocalPackagesBuildConfig'
  ${{ else }}:
    value: ''
- name: IncludeLocalPackagesBuildConfigTest
  ${{ if eq(parameters.includeLocalPackagesBuildConfig, true) }}:
    value: '1'
  ${{ else }}:
    value: ''

trigger:
  - master
  - releases/*

jobs:
- job: detect_changes
  displayName: Detect changes
  pool:
    vmImage: ubuntu-22.04
  steps:
  - script: |
      git fetch origin master
      git diff --name-only origin/master
      echo "##vso[task.setvariable variable=TASKS;isoutput=true]$(node ./ci/ci-test-tasks/detect-changed-tasks.js $(git diff --name-only origin/master))"
    displayName: 'Detect changed tasks'
    name: detect

- job: run_main_test_pipeline
  displayName: Run main test pipeline
  condition: |
    and(
      succeeded(),
      gt(length(dependencies.detect_changes.outputs['detect.TASKS']), 0)
    )
  dependsOn: detect_changes
  timeoutInMinutes: 360
  variables:
      - name: tasks
        value: $[dependencies.detect_changes.outputs['detect.TASKS']]
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    displayName: Use Node 24.x
    inputs:
      versionSpec: 24.x

  - script: |
      cd ./ci/ci-test-tasks/test-and-verify-v2
      npm i
      npm run build
    displayName: 'Build test pipelines runner'

  - script: |
      echo "Tasks to test: $(tasks)"
      node ./ci/ci-test-tasks/test-and-verify-v2 $(System.AccessToken) $(ADOUrl) $(System.TeamProject) $(tasks)
    displayName: 'Run test pipelines and verify results'
    failOnStderr: true
    env:
      USE_node20: ${{ parameters.USE_node20 }}
      usenode24withtaskhandler: ${{ parameters.usenode24withtaskhandler }}
