pr:
  - master
  
# Define the stages for the pipeline
stages:
- stage: Build
  jobs:
  - job: Build
    # Define the tasks for the job
    steps:
      - bash: |
          echo "##vso[task.setvariable variable=skipsubsequent;isOutput=true]true"
        displayName: 'Set variable'
        name: skipstep
    
    # Define a second job that depends on the first job
  - job: Test
    dependsOn: Build
    variables:
      - name: skipMe
        value: $[dependencies.Build.outputs['skipstep.skipsubsequent']]
    # Define the tasks for the job
    steps:
    - checkout: none
    - script: |
        echo $(skipMe)
      displayName: 'Print variable'
      continueOnError: true 