pr:
  - master
  
# Define the stages for the pipeline
stages:
- stage: Build
  jobs:
  - job: Build
    # Define the tasks for the job
    steps:
    - script: |
        echo "##vso[task.setvariable variable=myVar;isoutput=true]myValue"
      displayName: 'Set variable'
      name: setVarStep
    
    # Define a second job that depends on the first job
  - job: Test
    dependsOn: Build
    variables:
    - name: newVar
    - value: $[dependencies.Build.outputs['Build.myValue']]
    # Define the tasks for the job
    steps:
    - script: |
        echo $(Build.newVar)
      displayName: 'Print variable'
