pr:
  - master
  
# Define the stages for the pipeline
stages:
- stage: Build
  jobs:
  - job: Build
    # Define the tasks for the job
    steps:
    - task: Bash@3
      displayName: 'Set variable'
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=myVar;]myValue"
    
    # Define a second job that depends on the first job
  - job: Test
    dependsOn: Build
    # Define the tasks for the job
    steps:
    - task: Bash@3
      displayName: 'Print variable'
      inputs:
        targetType: 'inline'
        script: |
          echo $(myVar)