pr:
  - master

jobs:
- job: detect_changes
  displayName: Detect changes
  # we only test tasks on a PR and ignore forks since for security reasosns PAT tokens pipeline variable will not be available for fork's PRs.
  condition: and(eq(variables['build.reason'], 'PullRequest'), eq(variables['System.PullRequest.IsFork'], 'False'))
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: |
      git remote add ms https://github.com/microsoft/azure-pipelines-tasks.git
      git fetch ms master > tmp 2>&1 || cat tmp > '/tmp/stderr-contents-git_fetch.txt'
      git diff --name-only ms/master
      echo "##vso[task.setvariable variable=TASKS;isoutput=true]$(node ./ci/ci-test-tasks/detect-changed-tasks.js $(git diff --name-only ms/master))"
      echo Tasks: $(node ./ci/ci-test-tasks/detect-changed-tasks.js $(git diff --name-only ms/master))
    failOnStderr: true 
    displayName: 'Detect changed tasks'
    name: detect
 
- job: run_main_test_pipeline
  displayName: Run main test pipeline
  dependsOn: detect_changes
  variables:
      - name: tasks
        value: $[dependencies.detect_changes.outputs['detect.TASKS']]
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: none
  - script: |
      echo $(tasks)
      OUTPUT=`curl --user "":"$(ADOToken)" -H "Content-Type: application/json" -H "Accept:application/json" "$(CIMainUrl)" -X POST -d "{\"templateParameters\": { \"tasks\": \"$(tasks)\"}}"`
      echo $OUTPUT
    displayName: 'Run test pipelines'
