pr:
  - master

jobs:
- job: ci_test_tasks_init
  # we only test tasks on a PR and ignore forks since for security reasosns PAT tokens pipeline variable will not be available for fork's PRs.
  condition: and(eq(variables['build.reason'], 'PullRequest'), eq(variables['System.PullRequest.IsFork'], 'False'))
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: |
      git remote add ms https://github.com/microsoft/azure-pipelines-tasks.git
      git fetch ms
      git diff --name-only ms/master
      echo "##vso[task.setvariable variable=TASKS]$(node ./ci/ci-test-tasks/detect-updated-tasks.js $(git diff --name-only ms/master))"
      echo $(node ./ci/ci-test-tasks/detect-updated-tasks.js $(git diff --name-only ms/master))
    displayName: 'Detect updated tasks'
 
  - script: |
      echo $TASKS
      OUTPUT=`curl --user "":"$(ADOToken)" -H "Content-Type: application/json" -H "Accept:application/json" "$(CIMainUrl)" -X POST -d "{\"templateParameters\": { \"tasks\": \"$TASKS\"}}"`
      echo $OUTPUT
    displayName: 'Run test pipelines'