jobs:
- job: ci_test_tasks_init
  # we only test tasks on a PR and ignore forks since for security reasosns PAT tokens pipeline variable will not be available for fork's PRs.
  #condition: and(eq(variables['build.reason'], 'PullRequest'), eq(variables['System.PullRequest.IsFork'], 'False')) TODO: uncomment the line after testing
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: |
      npm install @octokit/core
      echo "##vso[task.setvariable variable=TASKS]$(node ./ci/ci-test-tasks/detect-updated-tasks.js $(PAT_Github))"
      echo $TASKS
    displayName: 'Detect updated tasks and extract task names'
 
  - script: |
      echo $TASKS
      OUTPUT=`curl --user "":"$(ADOToken)" -H "Content-Type: application/json" -H "Accept:application/json" "https://dev.azure.com/canary2-poc/tasks-canary/_apis/pipelines/5/runs?api-version=7" -X POST -d "{\"templateParameters\": { \"tasks\": \"$TASKS\"}}"`
      echo $OUTPUT
    displayName: 'Run test pipelines'