pr:
  - master
  
# Define the stages for the pipeline
stages:
- stage: Build
  jobs:
  - job: Build
    # Define the tasks for the job
    steps:
    - script: |
        echo "##vso[task.setvariable variable=myVar;isOutput=true]myValue"
      displayName: 'Set variable'
      name: setVarStep
    
    # Define a second job that depends on the first job
  - job: Test
    dependsOn: Build
    variables:
      - newVar: $[dependencies.Build.outputs['setVariable.myVar']]
    # Define the tasks for the job
    steps:
    - checkout: none
    - script: |
        echo $(Build.myVar)
      displayName: 'Print variable'
      continueOnError: true 

    - script: |
        echo $(Build.newVar)
      displayName: 'Print variable'
      continueOnError: true 
