pr:
  - master
  
# Define the stages for the pipeline
stages:
- stage: Build
  jobs:
  - job: Build
    # Define the tasks for the job
    steps:
    - script: |
        echo "##vso[task.setvariable variable=myVar]myValue"
      displayName: 'Set variable'
      name: setVarStep
      # Define the output variable
      outputs:
        myVar: $(setVarStep.variables.myVar)
    
    # Define a second job that depends on the first job
  - job: Test
    dependsOn: Build
    # Define the tasks for the job
    steps:
    - script: |
        echo $(Build.myVar)
      displayName: 'Print variable'
