parameters:
- name: tasks
  displayName: Tasks to process (separate by colons, no whitespaces)
  type: string
  default: DownloadPackageV1
- name: BuildSourceVersion
  displayName: The latest version control change of the triggering repo that is included in this build.
  type: string

trigger: none
pr: none

pool:
  vmImage: windows-2022

stages:
- stage: BuildAndTest
  condition: eq(variables['build.reason'], 'Manual')
  jobs:
    - ${{ each task in split(parameters.tasks, ',') }}:
      - job: ${{ task }}_build_task
        displayName: Build Task (${{ task }})
        steps:
        - template: ./build-task.yml
          parameters:
            task: ${{ task }}
            push: false
            publishArtifact: true
            patchVersion: true
            version: '0.999.0'
            BuildSourceVersion: ${{ parameters.BuildSourceVersion }}

    - job: tfx_init
      displayName: Tfx init
      steps:
      - template: ./tfx-init.yml

    - ${{ each task in split(parameters.tasks, ',') }}:
      - job: ${{ task }}_pre_delete
        displayName: PreDelete (${{ task }})
        steps:
        - template: ./delete-task.yml
          parameters:
            task: ${{ task }}

    - ${{ each task in split(parameters.tasks, ',') }}:
      - job: ${{ task }}_upload_task
        displayName: Upload (${{ task }})
        steps:
        - template: ./upload-task.yml
          parameters:
            task: ${{ task }}

    - ${{ each task in split(parameters.tasks, ',') }}:
      - job: ${{ task }}_test_task
        displayName: Test (${{ task }})
        steps:
        - template: ./test-task.yml
          parameters:
            task: ${{ task }}

    - ${{ each task in split(parameters.tasks, ',') }}:
      - job: ${{ task }}_post_delete
        displayName: PostDelete (${{ task }})
        steps:
        - template: ./delete-task.yml
          parameters:
            task: ${{ task }}
