parameters:
- name: tasks
  displayName: Tasks to process, separated by semicolons (for different tasks) and commas (beween different versions of the same task), no whitespaces
  type: string
  default: DownloadPackageV1
- name: BuildSourceVersion
  displayName: The latest version control change of the triggering repo that is included in this build.
  type: string

trigger: none
pr: none

stages:
- stage: ProcessAllTasks
  condition: eq(variables['build.reason'], 'Manual')
  jobs:
    - ${{ each task_versions in split(parameters.tasks, ';') }}:
      - job:  Process_${{ split(task_versions, ',')[0] }}
        displayName: Process ${{ task_versions }}
        pool:
          vmImage: windows-2022
        steps:
        # Start collect diagnostics
        - powershell: ./ci/start-collect-diagnostics.ps1
          displayName: Start collect diagnostics

        - template: ./build-init.yml
          parameters:
            BuildSourceVersion: ${{ parameters.BuildSourceVersion }}

        - template: ./test-init.yml

        - ${{ each task in split(task_versions, ',') }}:
          - template: ./build-task.yml
            parameters:
              task: ${{ task }}
              patchVersion: true
              version: '0.999.0'

          - template: ./test-task.yml
            parameters:
              task: ${{ task }}

        # Stop collect diagnostics
        - powershell: ./ci/stop-collect-diagnostics.ps1
          displayName: Stop collect diagnostics
          condition: always()
